integrations:

  agent:
    enabled: true

    relabel_configs:
    - action: replace
      source_labels:
      - agent_hostname
      target_label: instance

  node_exporter:
    enabled: true
    relabel_configs:
    - replacement: hostname
      target_label: instance

  prometheus_remote_write:
  - basic_auth:
      password: dummypass
      username: dummyuser
    url: https://prometheus-prod-10-prod-us-central-0.grafana.net/api/prom/push

    write_relabel_configs:
        - source_labels: [__name__]
          regex: "up|windows_cpu_time_total|windows_cs_hostname|windows_cs_logical_processors|windows_cs_physical_memory_bytes|windows_iis_current_connections|windows_logical_disk_free_bytes|windows_logical_disk_read_bytes_total|windows_logical_disk_size_bytes|windows_logical_disk_write_bytes_total|windows_net_bytes_total|windows_net_current_bandwidth|windows_os_info|windows_os_physical_memory_free_bytes|windows_system_system_up_time"
          action: keep

  windows_exporter:
    enabled: true

metrics:
  configs:
  - name: integrations
    remote_write:
    - basic_auth:
        password: dummypass
        username: dummyuser
      url: https://prometheus-prod-10-prod-us-central-0.grafana.net/api/prom/push

  global:
    scrape_interval: 60s  

    external_labels:

      #cloud_platform: AWS

  wal_directory: /tmp/grafana-agent-wal

